server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_demo
    username: ken
    password: 123456
  
  h2:
    console:
      enabled: true  # 設定要啟用 H2 的 console 可以在瀏覽器上面查詢 table
      path: '/h2' # 瀏覽器 console 的 URL 路徑
      
      
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update  # 當 spring boot entity 有修改時, 會自動修改 DB scheam