INSERT INTO DIC (DIC_TYPE, DIC_VALUE, DIC_KEY) VALUES ('CURRENCY', '美元', 'USD');
INSERT INTO DIC (DIC_TYPE, DIC_VALUE, DIC_KEY) VALUES ('CURRENCY', '英鎊', 'GBP');
INSERT INTO DIC (DIC_TYPE, DIC_VALUE, DIC_KEY) VALUES ('CURRENCY', '歐元', 'EUR');