CREATE TABLE
    DIC
    (
        DIC_TYPE VARCHAR2(30) NOT NULL,
        DIC_VALUE VARCHAR2(255) NOT NULL,
        DIC_KEY VARCHAR2(100) NOT NULL,
        CONSTRAINT PK_DIC PRIMARY KEY (DIC_TYPE, DIC_KEY)
    );